# site settings
title: decarcerate utah
email: decarcerateutah@gmail.com
description: a utah-based prison abolitionist group
baseurl: ''
url: 'https://www.decarcerateutah.org/'

# build settings
markdown: kramdown
include:
  - _pages
  - _events
paginate: 10
paginate_path: "/posts/:num/"
