# site settings
title: decarcerate utah
email: decarcerateutah@gmail.com
description: a prison abolitionist group
baseurl: ''
url: 'https://itscomputers.github.io/decarcerate'
twitter_username: decarcerateutah
github_username: itscomputers

# build settings
markdown: kramdown
include:
  - _pages
