# site settings
title: decarcerate utah
email: decarcerateutah@gmail.com
description: a prison abolitionist group
baseurl: ''
url: 'https://decarcerateutah.github.io/'
twitter_username: decarcerateutah
github_username: decarcerateutah

# build settings
markdown: kramdown
include:
  - _pages
  - _events
excerpt_separator: <!--more-->
